services:
  - type: web
    name: olx-monitor-bot
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CHECK_INTERVAL_SECONDS
        value: 120
      - key: PYTHON_VERSION
        value: 3.11.8
